project_id = "heupdkfdjdrbdwvzlywf"

[functions.enroll-and-invite]
verify_jwt = false

[functions.payments-notify]
verify_jwt = false

[functions.webhook]
verify_jwt = false

[functions.reply]
verify_jwt = false

[functions.email-track]
verify_jwt = false
